config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:new, :create, :show]
  resource :session, only: [:new, :create, :destroy]
  resources :bands
  resources :albums, except: [:index]
  resources :tracks, except: [:index]

end

app/models/album.rb
# == Schema Information
#
# Table name: albums
#
#  id         :integer          not null, primary key
#  band_id    :integer          not null
#  ttype      :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  name       :string           not null
#

class Album < ActiveRecord::Base
  has_many(
    :tracks,
    class_name: "Track",
    foreign_key: :album_id,
    primary_key: :id
    dependent: :destroy
    )

  belongs_to(
    :band,
    class_name: "Band",
    foreign_key: :band_id,
    primary_key: :id
  )
end

app/models/band.rb
# == Schema Information
#
# Table name: bands
#
#  id         :integer          not null, primary key
#  name       :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Band < ActiveRecord::Base


  has_many(
    :albums,
    class_name: "Album",
    foreign_key: :band_id,
    primary_key: :id,
    dependent: :destroy
  )

  has_many :tracks, through: :albums, source: :tracks

  def band_params
    params.require(:band).permit(:name)
  end
end

app/models/track.rb
# == Schema Information
#
# Table name: tracks
#
#  id         :integer          not null, primary key
#  album_id   :string           not null
#  track_type :string           not null
#  name       :string           not null
#  lyrics     :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Track < ActiveRecord::Base
  belongs_to(
    :album,
    class_name: "Album",
    foreign_key: :album_id,
    primary_key: :id
  )

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  email           :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ActiveRecord::Base
  validates :password, length: {minimum: 6, allow_nil: true}
  validates :session_token, presence: true
  after_initialize :ensure_session_token
  attr_reader :password

  def self.find_by_credentials(email, password)
    user = User.find_by(email: email)
    return nil if user.nil?
    user.is_password?(password) ? user : nil
  end

  def self.generate_session_token
    SecureRandom.urlsafe_base64(16)
  end

  # def self.first
  #   user_data = SQL.execute("SELECT * FROM users LIMIT 1") #=> {email: "jeff"}
  #   User.new(user_data)
  # end

  def reset_session_token!
    self.session_token = self.class.generate_session_token
    #as security measure so that hackers can't use the old session token to login
    #indefinitely
    self.save!
    self.session_token
  end

  def ensure_session_token
    self.session_token ||= User.generate_session_token
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end


end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  def login!(user)
    @current_user = user
    session[:session_token] = user.session_token
  end

  def current_user
    return nil if session[:session_token].nil?
    @current_user ||= User.find_by_session_token(session[:session_token])
  end

  def logout!
    current_user.reset_session_token!
    session[:session_token] = nil
  end

  def require_current_user!
    redirect_to new_session_url if current_user.nil?
  end


end

app/controllers/bands_controller.rb
class BandsController < ApplicationController
  def new
    @band = Band.new
  end

  def create
    @band = Band.new(band_params)
  end

  def show
  end

  def index
    @band = Band.all
  end

  def update
  end

  def destroy
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    # @user = User.new
    @user = User.new
  end

  def create
    user = User.find_by_credentials(
      params[:user][:email],
      params[:user][:password])

    if user.nil?
      redirect_to new_session_url
    else
      login!(user)

      # session[:session_token] = User.generate_session_token
      # @user.session_token = session[:session_token]
      # @user.save!
      redirect_to user_url(user)
      
    end
  end

  def destroy
    logout!
    redirect_to new_session_url
  end
end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_current_user!, except: [:create, :new]
  before_action :require_login, only: [:show]
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      login!(@user)
      redirect_to user_url(@user)
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  protected
  def user_params
    params.require(:user).permit(:email, :password)
  end

  def require_login
    unless current_user.id == params[:id].to_i
      redirect_to user_url(current_user)
    end
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bands_helper.rb
module BandsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tracks_helper.rb
module TracksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/bands/new.html.erb
<h1>Create a Band!</h1>

<form action ="<%= bands_url %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <label>Enter Band Name
    <input type="text" name="band[name]" value="">
  </label>
  <input type="submit" value="Create Band!">

</form>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MusicApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <% if !current_user.nil? %>
    <ul>
      <li>Logged in as: <%= current_user.email %></li>
      <li><form action="<%= session_url %>" method ="post">
        <input type ="hidden" name="_method" value="delete">
        <input type ="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
      <input type="submit" value="sign out!">
    </form></li>


    </ul>
    <% end %>

<%= yield %>

</body>
</html>

app/views/users/new.html.erb
<h1>New User Page</h1>

<form action="<%= users_url %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <label>
    Email
  <input type="text" name="user[email]" value="">
  </label>
  <label>
    Password
  <input type="password" name="user[password]" value="">
  </label>

  <input type="submit" value="Sign Up">
</form>

app/views/users/show.html.erb
<h1> Hi <%= @user.email %></h1>